DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255) NOT NULL);
-------------------
DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGINT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255) NOT NULL);
-------------------
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID BIGINT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(255) NOT NULL, PUBLICATION_DATE DATE NOT NULL);
-------------------
DROP TABLE IF EXISTS BOOK_AUTHOR_REL;
CREATE TABLE BOOK_AUTHOR_REL(
    BOOK_ID BIGINT NOT NULL,
    AUTHOR_ID BIGINT NOT NULL,
    PRIMARY KEY(BOOK_ID, AUTHOR_ID)
);
-------------------
